#!/usr/bin/env python3
"""Build AGENTS.md from bundled remorses/AGENTS.md fragments."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Iterable


UPSTREAM_REPO = "https://github.com/remorses/AGENTS.md"
UPSTREAM_COMMIT = "6b37c052626232f45885ad4bf94e128763069009"
ASSET_DIR = Path(__file__).resolve().parents[1] / "assets" / "remorses-agents-md"
GENERATED_MARKER = "Generated by agents-md-project-rules"

BASE_FRAGMENTS = ["core.md", "docs-writing.md", "github.md"]

PROFILES: dict[str, list[str]] = {
    "minimal": BASE_FRAGMENTS,
    "node": [
        *BASE_FRAGMENTS,
        "typescript.md",
        "pnpm.md",
        "vitest.md",
        "zod.md",
        "changelogs.md",
    ],
    "react": [
        *BASE_FRAGMENTS,
        "typescript.md",
        "pnpm.md",
        "react.md",
        "lucide.md",
        "vitest.md",
        "playwright.md",
        "zod.md",
        "changelogs.md",
    ],
    "react-router": [
        *BASE_FRAGMENTS,
        "typescript.md",
        "pnpm.md",
        "react.md",
        "react-router.md",
        "shadcn.md",
        "tailwind.md",
        "lucide.md",
        "vitest.md",
        "playwright.md",
        "zod.md",
        "sentry.md",
        "changelogs.md",
    ],
    "cli": [
        *BASE_FRAGMENTS,
        "typescript.md",
        "pnpm.md",
        "goke.md",
        "cac.md",
        "vitest.md",
        "zod.md",
        "changelogs.md",
    ],
    "api": [
        *BASE_FRAGMENTS,
        "typescript.md",
        "pnpm.md",
        "spiceflow.md",
        "zod.md",
        "sentry.md",
        "vitest.md",
        "changelogs.md",
    ],
    "threejs": [
        *BASE_FRAGMENTS,
        "typescript.md",
        "pnpm.md",
        "react.md",
        "threejs.md",
        "tailwind.md",
        "vitest.md",
        "playwright.md",
    ],
}


def available_fragments() -> list[str]:
    return sorted(path.name for path in ASSET_DIR.glob("*.md"))


def unique(items: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for item in items:
        if item not in seen:
            seen.add(item)
            result.append(item)
    return result


def load_package_json(project: Path) -> dict:
    path = project / "package.json"
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Invalid package.json: {exc}") from exc


def dependency_names(package_json: dict) -> set[str]:
    names: set[str] = set()
    for key in ("dependencies", "devDependencies", "peerDependencies", "optionalDependencies"):
        value = package_json.get(key, {})
        if isinstance(value, dict):
            names.update(value.keys())
    return names


def has_any_file(project: Path, names: Iterable[str]) -> bool:
    return any((project / name).exists() for name in names)


def has_glob(project: Path, pattern: str) -> bool:
    return next(project.glob(pattern), None) is not None


def detect_fragments(project: Path) -> list[str]:
    package_json = load_package_json(project)
    deps = dependency_names(package_json)
    fragments = [*BASE_FRAGMENTS]

    package_manager = str(package_json.get("packageManager", ""))
    if package_manager.startswith("pnpm") or (project / "pnpm-lock.yaml").exists():
        fragments.append("pnpm.md")

    if (
        "typescript" in deps
        or has_any_file(project, ["tsconfig.json", "tsconfig.base.json"])
        or has_glob(project, "**/*.ts")
        or has_glob(project, "**/*.tsx")
    ):
        fragments.append("typescript.md")

    if "react" in deps:
        fragments.append("react.md")
    if "react-router" in deps or "@remix-run/react" in deps:
        fragments.append("react-router.md")
    if "lucide-react" in deps:
        fragments.append("lucide.md")
    if "tailwindcss" in deps or has_any_file(project, ["tailwind.config.js", "tailwind.config.ts"]):
        fragments.append("tailwind.md")
    if (project / "components.json").exists():
        fragments.append("shadcn.md")
    if "vitest" in deps:
        fragments.append("vitest.md")
    if "@playwright/test" in deps or has_any_file(project, ["playwright.config.ts", "playwright.config.js"]):
        fragments.append("playwright.md")
    if "zod" in deps:
        fragments.append("zod.md")
    if "prisma" in deps or "@prisma/client" in deps or has_glob(project, "**/schema.prisma"):
        fragments.append("prisma.md")
    if any(name.startswith("@sentry/") or name == "sentry" for name in deps):
        fragments.append("sentry.md")
    if "stripe" in deps:
        fragments.append("stripe.md")
    if "ai" in deps:
        fragments.append("vercel-ai-sdk.md")
    if "three" in deps:
        fragments.append("threejs.md")
    if "spiceflow" in deps:
        fragments.append("spiceflow.md")
    if "goke" in deps or "@goke/mcp" in deps:
        fragments.extend(["goke.md", "cac.md"])
    elif "cac" in deps:
        fragments.append("cac.md")
    if "dedent" in deps or "string-dedent" in deps:
        fragments.append("dedent.md")
    if "errore" in deps:
        fragments.append("errore.md")
    if has_any_file(project, ["vercel.json"]):
        fragments.append("vercel.md")
    if has_any_file(project, ["fly.toml"]):
        fragments.append("fly.md")
    if has_any_file(project, ["doppler.yaml", "doppler.yml"]):
        fragments.append("doppler.md")
    if (project / ".changeset").exists() or (
        package_json.get("version") and package_json.get("private") is not True
    ):
        fragments.append("changelogs.md")

    return unique(fragments)


def resolve_fragment(name: str) -> Path:
    path = ASSET_DIR / name
    if not path.exists():
        available = ", ".join(available_fragments())
        raise SystemExit(f"Unknown fragment '{name}'. Available fragments: {available}")
    return path


def build_content(fragment_names: list[str], local_files: list[Path]) -> str:
    parts = [
        "<!--",
        f"{GENERATED_MARKER}.",
        f"Source: {UPSTREAM_REPO} @ {UPSTREAM_COMMIT}",
        "Fragments: " + ", ".join(fragment_names),
        "-->",
        "",
    ]

    for name in fragment_names:
        parts.append(resolve_fragment(name).read_text().rstrip())
        parts.append("")

    for path in local_files:
        if not path.exists():
            raise SystemExit(f"Local file not found: {path}")
        parts.append(path.read_text().rstrip())
        parts.append("")

    return "\n".join(parts).rstrip() + "\n"


def write_output(path: Path, content: str, force: bool) -> None:
    if path.exists() and not force:
        existing = path.read_text(errors="replace")
        if GENERATED_MARKER not in existing:
            raise SystemExit(
                f"{path} already exists and does not look generated by this plugin. "
                "Use --output AGENTS.generated.md, merge manually, or pass --force."
            )
    path.write_text(content)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("fragments", nargs="*", help="Fragment filenames, for example core.md")
    parser.add_argument("--profile", choices=sorted(PROFILES), help="Named fragment profile")
    parser.add_argument(
        "--detect",
        nargs="?",
        const=".",
        metavar="PROJECT_ROOT",
        help="Detect fragments from a project root, defaulting to current directory",
    )
    parser.add_argument(
        "--local",
        action="append",
        default=[],
        type=Path,
        help="Append a local markdown file after bundled fragments",
    )
    parser.add_argument("--output", default="AGENTS.md", type=Path, help="Output file path")
    parser.add_argument("--force", action="store_true", help="Overwrite an existing hand-written file")
    parser.add_argument("--list", action="store_true", help="List available fragments and profiles")
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    if args.list:
        print("Profiles:")
        for name, fragments in sorted(PROFILES.items()):
            print(f"  {name}: {' '.join(fragments)}")
        print("\nFragments:")
        for name in available_fragments():
            print(f"  {name}")
        return 0

    selected: list[str] = []
    if args.profile:
        selected.extend(PROFILES[args.profile])
    if args.detect is not None:
        selected.extend(detect_fragments(Path(args.detect).resolve()))
    selected.extend(args.fragments)
    selected = unique(selected or PROFILES["minimal"])

    content = build_content(selected, [path.resolve() for path in args.local])
    write_output(args.output, content, args.force)
    print(f"Wrote {args.output} with {len(selected)} fragment(s): {', '.join(selected)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
